"""Official Python client for the HTML/CSS to Image API."""

from ._version import __version__
from .client import HtmlCssToImageClient
from .exceptions import UnexpectedResponseError
from .models import (
    ApiErrorResponse,
    BaseCreateImageRequest,
    BatchCreateImageRequest,
    ColorSchemeType,
    CreateHtmlCssImageRequest,
    CreateImageBatchResponse,
    CreateImageBatchSuccessResponse,
    CreateImageRequest,
    CreateImageResponse,
    CreateImageSuccessResponse,
    CreateTemplatedImageRequest,
    CreateUrlImageRequest,
    DeleteImageResponse,
    DeleteImageSuccessResponse,
    ImageFormat,
    MediaType,
    PDFMargins,
    PDFOptions,
    PDFUnit,
    PDFValueInput,
    PDFValueWithUnits,
    RenderImageAspectRatio,
    RenderImageCrop,
    RenderImageCropOrigin,
    RenderImageCropPosition,
    RenderImageCropSize,
    RenderImageCropSpan,
    RenderImageFormat,
    RenderImageOptions,
    RenderImageValueUnit,
    ValidationError,
)

__all__ = [
    "ApiErrorResponse",
    "BaseCreateImageRequest",
    "BatchCreateImageRequest",
    "ColorSchemeType",
    "CreateHtmlCssImageRequest",
    "CreateImageBatchResponse",
    "CreateImageBatchSuccessResponse",
    "CreateImageRequest",
    "CreateImageResponse",
    "CreateImageSuccessResponse",
    "CreateTemplatedImageRequest",
    "CreateUrlImageRequest",
    "DeleteImageResponse",
    "DeleteImageSuccessResponse",
    "HtmlCssToImageClient",
    "ImageFormat",
    "MediaType",
    "PDFMargins",
    "PDFOptions",
    "PDFUnit",
    "PDFValueInput",
    "PDFValueWithUnits",
    "RenderImageAspectRatio",
    "RenderImageCrop",
    "RenderImageCropOrigin",
    "RenderImageCropPosition",
    "RenderImageCropSize",
    "RenderImageCropSpan",
    "RenderImageFormat",
    "RenderImageOptions",
    "RenderImageValueUnit",
    "UnexpectedResponseError",
    "ValidationError",
    "__version__",
]
